add_requires("cmake::DtkCore",{system=true})
add_requires("doxygen",{system=true})
add_requires("apt::qtbase5-dev",{system=true})
add_requires("apt::libglib2.0-dev",{system=true})
add_requires("apt::libnm-dev",{system=true})

package("libnm")
	add_extsources("pkgconfig::libnm")

package("gio-2.0")
	add_extsources("pkgconfig::gio-2.0")

target("dtknetworkmanager")
	set_basename("dtknetworkmanager")
	set_warnings("allextra")
	set_optimize("faster")
	set_languages("cxx17")
	set_targetdir("build")
	set_installdir("/usr")
	add_packages("cmake::DtkCore")
	add_packages("libnm")
	add_packages("gio-2.0")
	add_rules("qt.shared")
	add_includedirs("include")
	add_installfiles("include/*.h","include/settings/*.h",{prefixdir="dtknetworkmanager"})
	add_files("./src/**.cpp","./src/**.h")
	add_frameworks("QtCore","QtNetwork","QtDBus")
	add_links("dtkcore","nm","gio-2.0")
